version: "3.7"

x-common-props: &common-props
  build:
    context: ./
    target: base
  working_dir: /base
  volumes:
    - ./:/base
    - node_modules:/base/node_modules

services:

  npm:
    <<: *common-props
    entrypoint: npm

  dev:
    <<: *common-props
    ports:
      - "3000:3000"
    command: npm run dev

  prod:
    build:
      context: ./
      network: host
      args:
      - SHARP_URL=${SHARP_URL}
    ports:
      - "3000:3000"
    restart: always
  
volumes:
  node_modules:
