version: "3.7"

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data

  app:
    container_name: my_blog
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    restart: always
    ports:
      - "3000:3000"
  