version: "3.7"

x-common-props: &common-props
  build:
    context: ./
    target: base
  working_dir: /base
  volumes:
    - ./:/base
    - node_modules:/base/node_modules

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ${PGDATA_DIR}:/var/lib/postgresql/data
    ports:
      - "8001:5432"
    
  npm:
    <<: *common-props
    entrypoint: npm

  dev:
    <<: *common-props
    depends_on:
      - db
    ports:
      - "3000:3000"
    command: npm run dev

  prod:
    build:
      context: ./
      network: my-blog_default
    depends_on:
      - db
    ports:
      - "3000:3000"
  
volumes:
  node_modules:
